In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

In [2]:
# Reading in the Data and looking at the first 10 rows
# Data can be found at 
survival = pd.read_csv("../Kaggle_Data/gender_submission.csv")
survival.head(10)

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1
5          897         0
6          898         1
7          899         0
8          900         1
9          901         0

In [3]:
#Check for NaNs 
survival[survival.isnull().any(axis=1)]
#No Nans in the table

Empty DataFrame
Columns: [PassengerId, Survived]
Index: []

In [37]:
test_data = pd.read_csv("../Kaggle_Data/test.csv")
test_data.head(10)

test_null_rows = test_data[test_data.isnull().any(axis=1)].shape[0]
# We find that 331 rows have null values
total_test_rows = test_data.shape[0]


test_null_rows / total_test_rows
# 79.2% of the rows have null values, so it might be important to check which specific columns have thes null values, may be wise to drop that column later on

0.7918660287081339

In [46]:
#Merging the test dataframe to have the survival as well

full_df = test_data.merge(survival,how="right",left_on="PassengerId", right_on="PassengerId")

#Dropping names, do not think it would be a huge factor

full_df = full_df.drop(columns="Name")

In [47]:
full_df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,892,3,male,34.5,0,0,330911,7.8292,NaN,Q,0
1,893,3,female,47.0,1,0,363272,7.0000,NaN,S,1
2,894,2,male,62.0,0,0,240276,9.6875,NaN,Q,0
3,895,3,male,27.0,0,0,315154,8.6625,NaN,S,0
4,896,3,female,22.0,1,1,3101298,12.2875,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0
414,1306,1,female,39.0,0,0,PC 17758,108.9000,C105,C,1
415,1307,3,male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0
416,1308,3,male,NaN,0,0,359309,8.0500,NaN,S,0
417,1309,3,male,NaN,1,1,2668,22.3583,NaN,C,0

In [ ]:
# Turning sex into dummy variables, One-hot encoding
pd.get_dummies(full_df)

#May have to look for nans in each row, also look into the unique cabins

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Survived,Sex_female,Sex_male,Ticket_110469,...,Cabin_F E46,Cabin_F E57,Cabin_F G63,Cabin_F2,Cabin_F33,Cabin_F4,Cabin_G6,Embarked_C,Embarked_Q,Embarked_S
0,892,3,34.5,0,0,7.8292,0,False,True,False,...,False,False,False,False,False,False,False,False,True,False
1,893,3,47.0,1,0,7.0000,1,True,False,False,...,False,False,False,False,False,False,False,False,False,True
2,894,2,62.0,0,0,9.6875,0,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,895,3,27.0,0,0,8.6625,0,False,True,False,...,False,False,False,False,False,False,False,False,False,True
4,896,3,22.0,1,1,12.2875,1,True,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,NaN,0,0,8.0500,0,False,True,False,...,False,False,False,False,False,False,False,False,False,True
414,1306,1,39.0,0,0,108.9000,1,True,False,False,...,False,False,False,False,False,False,False,True,False,False
415,1307,3,38.5,0,0,7.2500,0,False,True,False,...,False,False,False,False,False,False,False,False,False,True
416,1308,3,NaN,0,0,8.0500,0,False,True,False,...,False,False,False,False,False,False,False,False,False,True
417,1309,3,NaN,1,1,22.3583,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False

In [51]:
#Incorporate Titanic branch