In [39]:
# Create markdown cells to document processes

In [ ]:
# Variables defined

# survival	Survival	0 = No, 1 = Yes
# pclass	Ticket class	1 = 1st, 2 = 2nd, 3 = 3rd
# sex	Sex	
# Age	Age in years	
# sibsp	# of siblings / spouses aboard the Titanic	
# parch	# of parents / children aboard the Titanic	
# ticket	Ticket number	
# fare	Passenger fare	
# cabin	Cabin number	
# embarked	Port of Embarkation	C = Cherbourg, Q = Queenstown, S = Southampton

In [25]:
import pandas as pd

print(pd.__version__)

2.3.3

In [2]:
# Reading in the Data and looking at the first 10 rows
# Data can be found at 
survival = pd.read_csv("../Kaggle_Data/gender_submission.csv")
survival.head(10)

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1
5          897         0
6          898         1
7          899         0
8          900         1
9          901         0

In [3]:
#Check for NaNs 
survival[survival.isnull().any(axis=1)]
#No Nans in the table

Empty DataFrame
Columns: [PassengerId, Survived]
Index: []

In [4]:
test_data = pd.read_csv("../Kaggle_Data/test.csv")
test_data.head(10)

test_null_rows = test_data[test_data.isnull().any(axis=1)].shape[0]
# We find that 331 rows have null values
total_test_rows = test_data.shape[0]


test_null_rows / total_test_rows
# 79.2% of the rows have null values, so it might be important to check which specific columns have thes null values, may be wise to drop that column later on

0.7918660287081339

In [15]:
#Merging the test dataframe to have the survival as well

test_with_survival_df = test_data.merge(survival,how="right",left_on="PassengerId", right_on="PassengerId")

#Dropping names, do not think it would be a huge factor

test_with_survival_df = test_with_survival_df.drop(columns="Name")

In [16]:
test_with_survival_df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,892,3,male,34.5,0,0,330911,7.8292,NaN,Q,0
1,893,3,female,47.0,1,0,363272,7.0000,NaN,S,1
2,894,2,male,62.0,0,0,240276,9.6875,NaN,Q,0
3,895,3,male,27.0,0,0,315154,8.6625,NaN,S,0
4,896,3,female,22.0,1,1,3101298,12.2875,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0
414,1306,1,female,39.0,0,0,PC 17758,108.9000,C105,C,1
415,1307,3,male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0
416,1308,3,male,NaN,0,0,359309,8.0500,NaN,S,0
417,1309,3,male,NaN,1,1,2668,22.3583,NaN,C,0

In [ ]:
# Turning sex into dummy variables, One-hot encoding
sex_onehot = pd.get_dummies(test_with_survival_df[["Sex", "PassengerId"]], dtype="int")

full_df = test_with_survival_df.merge(right= sex_onehot, how= "left")
#Merged sex encoding with rest of df

In [ ]:
#May have to look for nans in each row, also look into the unique cabins

#Looking through the full_df around other columns to check for repeatability

full_df["Cabin"].value_counts()
#The highest mode is 3

#Investigating where cabin numbers repeated most
full_df[full_df["Cabin"] == "B57 B59 B63 B66"]
#This most likely means they are in the same Cabin, maybe there is a way to check if number of people in a cabin was a factor (Maybe it confounds with sibsp or parch, can check later)



#Is there a way to map their ticket or some other variable onto their position on the ship

#Based of Cabin positions it seems Upper Deck was E, Saloon deck D, Shelter Deck C, Bridge deck B

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived,Sex_female,Sex_male
24,916,1,female,48.0,1,3,PC 17608,262.375,B57 B59 B63 B66,C,1,1,0
64,956,1,male,13.0,2,2,PC 17608,262.375,B57 B59 B63 B66,C,0,0,1
142,1034,1,male,61.0,1,3,PC 17608,262.375,B57 B59 B63 B66,C,0,0,1