In [35]:
import pandas as pd

print(pd.__version__)

2.3.3

In [ ]:
# Reading in the Data and looking at the first 10 rows
# Data can be found at 
survival = pd.read_csv("../Kaggle_Data/gender_submission.csv")
survival.head(10)

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1
5          897         0
6          898         1
7          899         0
8          900         1
9          901         0

In [24]:
#Check for NaNs 
survival[survival.isnull().any(axis=1)]
#No Nans in the table

Empty DataFrame
Columns: [PassengerId, Survived]
Index: []

In [ ]:
test_data = pd.read_csv("../Kaggle_Data/test.csv")
test_data.head(10)

test_null_rows = test_data[test_data.isnull().any(axis=1)].shape[0]
# We find that 331 rows have null values
total_test_rows = test_data.shape[0]


test_null_rows / total_test_rows
# 79.2% of the rows have null values, so it might be important to check which specific columns have thes null values, may be wise to drop that column later on

0.7918660287081339